# Generated by Django 5.2.5 on 2025-09-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EVStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("num_chargers", models.IntegerField(blank=True, default=1, null=True)),
                ("charger_types", models.CharField(max_length=200)),
                ("availability_status", models.BooleanField(default=True)),
            ],
        ),
    ]
