# Generated by Django 5.2.5 on 2025-09-07 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Map", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evstation",
            name="availability_status",
        ),
        migrations.RemoveField(
            model_name="evstation",
            name="num_chargers",
        ),
    ]
