# Generated by Django 5.2.5 on 2025-09-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Map", "0002_remove_evstation_availability_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evstation",
            name="availability_status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="evstation",
            name="num_chargers",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
