# Generated by Django 5.2.5 on 2025-09-07 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Map", "0004_vehicle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="user",
        ),
    ]
