# Generated by Django 5.2.5 on 2025-12-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Map", "0005_remove_vehicle_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evstation",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
