# Generated by Django 5.2.5 on 2025-12-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Map", "0007_checkin"),
    ]

    operations = [
        migrations.AddField(
            model_name="evstation",
            name="image",
            field=models.ImageField(
                blank=True,
                default="media/stations/OIP.jpg",
                null=True,
                upload_to="media/stations/",
            ),
        ),
    ]
