# Generated by Django 5.2.5 on 2025-12-22 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Map", "0009_alter_evstation_image_bookmark"),
    ]

    operations = [
        migrations.CreateModel(
            name="EVStationImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="stations/gallery/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="Map.evstation",
                    ),
                ),
            ],
        ),
    ]
