# Generated by Django 6.0.5 on 2026-05-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0011_alter_evstation_options_evstation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evstation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stations/'),
        ),
    ]
